version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      ADB_INSTALL_TIMEOUT: "10"
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: 
          name: Download dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      - run: 
          name: Unit test
          command: ./gradlew testDebugUnitTest
      
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-25;google_apis;armeabi-v7a" && echo "no" | avdmanager create avd -n my-avd -k "system-images;android-25;google_apis;armeabi-v7a"

      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd my-avd -noaudio -no-boot-anim -no-window -accel auto -verbose
          background: true

      - run:
          name: Wait emulator
          command: |
            circle-android wait-for-boot
            sleep 30
            adb shell input keyevent 82

      - run:
          name: Run Espresso tests
          command: |
            ./gradlew connectedDebugAndroidTest -PdisablePreDex

      - store_artifacts:
          path: app/build/reports
          destination: reports
          
      - store_test_results:
          path: app/build/test-results
